blog_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from first_app import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'first_app/',include('first_app.urls')),
    url(r'^web/',include('web.urls'))
]

web/urls.py
from django.conf.urls import url
from web.views import account
from web.views import home
from web.views import project_list
from django.conf.urls import include
from web.views import manage
from web.views import wiki
from web.views import file
from web.views import setting
from web.views import issues
from web.views import dashboard
from web.views import essay
urlpatterns=[
            url(r'^sign_up/$',account.sign_up,name='sign_up'),
            url(r'^send_sms/$',account.send_sms,name='send_sms'),
            url(r'^sign_in/sms/$',account.sign_in_sms,name='sign_in_sms'),
            url(r'^sign_in/$',account.sign_in,name='sign_in'),
            url(r'^image/code/$',account.image_code,name='image_code'),
            url(r'^index/$',home.index,name='index'),
            url(r'^signout/$',account.signout,name='signout'),
            url(r'^project/list/$',project_list.project_list,name='project_list'),
            url(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$',project_list.project_star,name='project_star'),
            url(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$',project_list.project_unstar,name='project_unstar'),

            url(r'^price/$', home.price, name='price'),
            url(r'^payment/(?P<policy_id>\d+)/$', home.payment, name='payment'),
            url(r'^pay/$', home.pay, name='pay'),
            url(r'^pay/notify/$', home.pay_notify, name='pay_notify'),

            url(r'^latest/essay/$',essay.latest_essay,name='latest_essay'),

            url(r'^manage/(?P<project_id>\d+)/',include([


                url(r'^statistic/$',manage.statistic,name='statistic'),

                url(r'^wiki/$',wiki.wiki,name='wiki'),
                url(r'^wiki/add/$',wiki.wiki_add,name='wiki_add'),
                url(r'^wiki/catalog/$',wiki.wiki_catalog,name='wiki_catalog'),
                url(r'^wiki/delete/(?P<wiki_id>\d+)$',wiki.wiki_delete,name='wiki_delete'),
                url(r'^wiki/edit/(?P<wiki_id>\d+)$',wiki.wiki_edit,name='wiki_edit'),
                url(r'^wiki/uoload/$',wiki.wiki_upload,name='wiki_upload'),

                url(r'^file/$',file.file,name='file'),
                url(r'^file_delete/$',file.file_delete,name='file_delete'),
                url(r'^file/post/$',file.file_post,name='file_post'),
                url(r'^file/download/(?P<file_id>\d+)$',file.download,name='file_download'),
                url(r'^cos/credential/$',file.cos_credential,name='cos_credential'),


                url(r'^setting/$',setting.setting,name='setting'),
                url(r'^setting/delete$',setting.delete,name='setting_delete'),

                url(r'^issues/$', issues.issues, name='issues'),
                url(r'^issues/detail/(?P<issues_id>\d+)/$', issues.issues_detail, name='issues_detail'),
                url(r'^issues/record/(?P<issues_id>\d+)/$', issues.issues_record, name='issues_record'),
                url(r'^issues/change/(?P<issues_id>\d+)/$', issues.issues_change, name='issues_change'),
                url(r'^issues/invite/url/$', issues.invite_url, name='invite_url'),

                url(r'^dashboard/$', dashboard.dashboard, name='dashboard'),
                url(r'^dashboard/issues/chart/$', dashboard.issues_chart, name='issues_chart'),
            ],None,None)),

            url(r'^invite/join/(?P<code>\w+)/$',issues.invite_join, name='invite_join'),
]

web/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    username=models.CharField(max_length=32)
    email=models.EmailField(max_length=32)
    mobile_phone=models.CharField(max_length=15)
    password=models.CharField(max_length=32)

    # price_policy=models.ForeignKey(verbose_name='价格策略',to='PricePolicy',null=True,blank=True)(可以提升性能)

class PricePolicy(models.Model):
    """价格策略"""
    category_choices=(
        (1,'免费版'),
        (2,'收费版'),
        (3,'其它版')
    )
    category=models.SmallIntegerField(verbose_name='收费类型',default=1,choices=category_choices)
    title=models.CharField(verbose_name='标题',max_length=32)
    price=models.PositiveIntegerField(verbose_name='价格')#正整数类型

    project_num=models.PositiveIntegerField(verbose_name='项目数')
    project_member=models.PositiveIntegerField(verbose_name='项目成员数')
    project_space=models.PositiveIntegerField(verbose_name='单项目空间')
    per_file_size=models.PositiveIntegerField(verbose_name='单文件大小（M）')

    create_datetime=models.DateTimeField(verbose_name='创建时间',auto_now_add=True)

class Transaction(models.Model):
    """交易记录"""
    status_choice=(
        (1,'未支付'),
        (2,'已支付')
    )

    status=models.SmallIntegerField(verbose_name='支付状态',choices=status_choice)
    order=models.CharField(verbose_name='订单号',max_length=64,unique=True)#唯一索引
    user=models.ForeignKey(verbose_name='用户',to='UserInfo')
    price_policy=models.ForeignKey(verbose_name='价格策略',to='PricePolicy')
    count=models.IntegerField(verbose_name='数量（年）',help_text='0表示无限期')

    price=models.IntegerField(verbose_name='实际支付价格')

    start_datetime=models.DateTimeField(verbose_name='开始时间',null=True,blank=True)
    end_datetime=models.DateTimeField(verbose_name='结束时间',null=True,blank=True)

    create_datetime=models.DateTimeField(verbose_name='创建时间',auto_now_add=True)

class Project(models.Model):
    """项目表"""
    COLOR_CHOICES=(
        (1,'#56b8eb'),
        (2,'#f28033'),
        (3,'#ebc656'),
        (4,'#a2d148'),
        (5,'#20BFA4'),
        (6,'#7461c2'),
        (7,'#20bfa3')
    )
    name=models.CharField(verbose_name='博客名',max_length=32)
    color=models.SmallIntegerField(verbose_name='风格',choices=COLOR_CHOICES,default=1)
    desc=models.CharField(verbose_name='博客概述',max_length=255,null=True,blank=True)
    user_space=models.BigIntegerField(verbose_name='项目已使用空间',default=0)
    star=models.BooleanField(verbose_name='星标',default=False)

    # bucket=models.CharField(verbose_name='腾讯对象储存桶',max_length=128)
    # region=models.CharField(verbose_name='腾讯对象储存区域',max_length=32)

    join_count=models.SmallIntegerField(verbose_name='参与人数',default=1)
    creator=models.ForeignKey(verbose_name='创建者',to='UserInfo')
    create_datetime=models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    bucket=models.CharField(verbose_name='cos桶',max_length=128)
    region=models.CharField(verbose_name='cos区域',max_length=32)

class ProjectUser(models.Model):
    """项目参与者"""
    user=models.ForeignKey(verbose_name='参与者',to='UserInfo')#,related_name='projects'
    project=models.ForeignKey(verbose_name='项目',to='Project')
    star = models.BooleanField(verbose_name='星标', default=False)
    # invitee=models.ForeignKey(verbose_name='邀请者',to='UserInfo')#,related_name='invites',null=True,blank=True



    create_datetime=models.DateTimeField(verbose_name='加入时间',auto_now_add=True)


class Wiki(models.Model):
    project=models.ForeignKey(verbose_name='项目',to='Project')
    title=models.CharField(verbose_name='标题',max_length=32)
    content=models.TextField(verbose_name='内容')
    depth=models.IntegerField(verbose_name='深度',default=1)
    #子关联
    parent=models.ForeignKey(verbose_name='父文章',to='self',null=True,blank=True,related_name='children')

    def __str__(self):
        return self.title

class FileRepository(models.Model):
    project=models.ForeignKey(verbose_name='项目',to='Project')
    file_type_choice=(
        (1,'文件'),
        (2,'文件夹')
    )
    file_type=models.SmallIntegerField(verbose_name='类型',choices=file_type_choice)
    name=models.CharField(verbose_name='文件夹名称',max_length=32,help_text="w文件/文件夹")
    key=models.CharField(verbose_name="文件储存在cos中的KEY",max_length=128,null=True,blank=True)

    file_size=models.IntegerField(verbose_name='文件大小',null=True,blank=True)
    file_path=models.CharField(verbose_name='文件路径',max_length=255,null=True,blank=True)
    parent=models.ForeignKey(verbose_name='父级目录',to='self',related_name='child',null=True,blank=True)

    update_user=models.ForeignKey(verbose_name='最近更新者',to='UserInfo')
    update_datetime=models.DateTimeField(verbose_name='更新时间',auto_now=True)


class Issues(models.Model):
    """ 问题 """
    project = models.ForeignKey(verbose_name='项目', to='Project')
    issues_type = models.ForeignKey(verbose_name='问题类型', to='IssuesType')
    module = models.ForeignKey(verbose_name='模块', to='Module', null=True, blank=True)
    subject = models.CharField(verbose_name='主题', max_length=80)
    desc = models.TextField(verbose_name='问题描述')
    priority_choices = (
        ("danger", "高"),
        ("warning", "中"),
        ("success", "低"),
    )
    priority = models.CharField(verbose_name='优先级', max_length=12, choices=priority_choices, default='danger')

    # 新建、处理中、已解决、已忽略、待反馈、已关闭、重新打开
    status_choices = (
        (1, '新建'),
        (2, '处理中'),
        (3, '已解决'),
        (4, '已忽略'),
        (5, '待反馈'),
        (6, '已关闭'),
        (7, '重新打开'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)

    assign = models.ForeignKey(verbose_name='指派', to='UserInfo', related_name='task', null=True, blank=True)
    attention = models.ManyToManyField(verbose_name='关注者', to='UserInfo', related_name='observe', blank=True)

    start_date = models.DateField(verbose_name='开始时间', null=True, blank=True)
    end_date = models.DateField(verbose_name='结束时间', null=True, blank=True)
    mode_choices = (
        (1, '公开模式'),
        (2, '隐私模式'),
    )
    mode = models.SmallIntegerField(verbose_name='模式', choices=mode_choices, default=1)

    parent = models.ForeignKey(verbose_name='父问题', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.SET_NULL)

    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_problems')

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    latest_update_datetime = models.DateTimeField(verbose_name='最后更新时间', auto_now=True)

    def __str__(self):
        return self.subject


class Module(models.Model):
    """ 模块（里程碑）"""
    project = models.ForeignKey(verbose_name='项目', to='Project')
    title = models.CharField(verbose_name='模块名称', max_length=32)

    def __str__(self):
        return self.title


class IssuesType(models.Model):
    """ 问题类型 例如：任务、功能、Bug """

    PROJECT_INIT_LIST = ["任务", '功能', 'Bug']

    title = models.CharField(verbose_name='类型名称', max_length=32)
    project = models.ForeignKey(verbose_name='项目', to='Project')

    def __str__(self):
        return self.title

class IssuesReply(models.Model):
    """ 问题回复"""

    reply_type_choices = (
        (1, '修改记录'),
        (2, '回复')
    )
    reply_type = models.IntegerField(verbose_name='类型', choices=reply_type_choices)

    issues = models.ForeignKey(verbose_name='问题', to='Issues')
    content = models.TextField(verbose_name='描述')
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_reply')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复', to='self', null=True, blank=True)


class ProjectInvite(models.Model):
    """ 项目邀请码 """
    project = models.ForeignKey(verbose_name='项目', to='Project')
    code = models.CharField(verbose_name='邀请码', max_length=64, unique=True)
    count = models.PositiveIntegerField(verbose_name='限制数量', null=True, blank=True, help_text='空表示无数量限制')
    use_count = models.PositiveIntegerField(verbose_name='已邀请数量', default=0)
    period_choices = (
        (30, '30分钟'),
        (60, '1小时'),
        (300, '5小时'),
        (1440, '24小时'),
    )
    period = models.IntegerField(verbose_name='有效期', choices=period_choices, default=1440)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_invite')

web/forms/wiki.py
from web import models
from django import forms
from web.forms.bootstrap import BootStrap

class WikiModelForm(BootStrap,forms.ModelForm):

    class Meta:
        model=models.Wiki
        exclude=['project','depth']
    def __init__(self,request,*args,**kwargs):
        super().__init__(*args,**kwargs)

        #找到想要的字段把他绑定显示的数据重置
        #数据=去数据库获取的当前项目所有Wiki标题
        total_list=[("","请选择")]
        data_list=models.Wiki.objects.filter(project=request.blog.project).values_list('id','title')
        total_list.extend(data_list)
        self.fields['parent'].choices=total_list

web/views/dashboard.py
import time
import datetime
import collections
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import Count
from web import models


def dashboard(request, project_id):
    """ 概览 """

    # 问题数据处理
    status_dict = collections.OrderedDict()
    for key, text in models.Issues.status_choices:
        status_dict[key] = {'text': text, 'count': 0}

    issues_data = models.Issues.objects.filter(project_id=project_id).values('status').annotate(ct=Count('id'))
    for item in issues_data:
        status_dict[item['status']]['count'] = item['ct']

    # 项目成员
    user_list = models.ProjectUser.objects.filter(project_id=project_id).values('user_id', 'user__username')

    # 最近的10个问题
    top_ten = models.Issues.objects.filter(project_id=project_id, assign__isnull=False).order_by('-id')[0:10]

    context = {
        'status_dict': status_dict,
        'user_list': user_list,
        'top_ten_object': top_ten
    }
    return render(request, 'dashboard.html', context)


def issues_chart(request, project_id):
    """ 在概览页面生成highcharts所需的数据 """
    today = datetime.datetime.now().date()
    date_dict = collections.OrderedDict()
    for i in range(0, 30):
        date = today - datetime.timedelta(days=i)
        date_dict[date.strftime("%Y-%m-%d")] = [time.mktime(date.timetuple()) * 1000, 0]
    print(date_dict)
    # select xxxx,1 as ctime from xxxx
    # select id,name,email from table;
    # select id,name, strftime("%Y-%m-%d",create_datetime) as ctime from table;
    # "DATE_FORMAT(web_transaction.create_datetime,'%%Y-%%m-%%d')"
    result = models.Issues.objects.filter(project_id=project_id,
                                          create_datetime__gte=today - datetime.timedelta(days=30)).extra(
        select={'ctime': "strftime('%%Y-%%m-%%d',web_issues.create_datetime)"}).values('ctime').annotate(ct=Count('id'))
    print(result)
    for item in result:
        date_dict[item['ctime']][1] = item['ct']

    return JsonResponse({'status': True, 'data': list(date_dict.values())})

web/views/project_list.py
from django.http import JsonResponse,HttpResponse
from django.shortcuts import render,redirect
from web.forms.project import ProjectMdoelForm
from web import models
from utils.tencent.cos import create_bucket
import time
def project_list(request):
    if request.method=='GET':
        """
        从数据库获取两部分数据
        我创建的所有项目：已星标，未星标
        我参与的所有项目：已星标，未星标
        
        提取已星标
        
        将得到三个列表
        """
        project_dict={'star':[],'my':[],'join':[]}

        my_project_list=models.Project.objects.filter(creator=request.blog.user)
        for row in  my_project_list:
            if row.star:
                project_dict['star'].append({'value':row,'type':'my'})
            else:
                project_dict['my'].append(row)
        join_project_list=models.ProjectUser.objects.filter(user=request.blog.user)
        for item in join_project_list:
            if item.star:
                project_dict['star'].append({'value':item.project,'type':'join'})
            else:
                project_dict['join'].append(item.project)
        form=ProjectMdoelForm(request)
        return render(request,'project_list.html',{'form':form,'project_dict':project_dict})
    form=ProjectMdoelForm(request,data=request.POST)
    if form.is_valid():
        #为项目创建cos桶
        #构建唯一桶名称手机号，时间
        bucket="{}-{}-1303841926".format(request.blog.user.mobile_phone,str(int(time.time())))
        region="ap-chengdu"
        create_bucket(bucket,region)
        #将桶和区域存储
        form.instance.bucket=bucket
        form.instance.region=region
        #验证通过 用户仅提供博客名，风格，描述，还有一些字段尚未给出
        form.instance.creator=request.blog.user
        #创建项目
        instance=form.save()
        # 3.项目初始化问题类型
        issues_type_object_list = []
        for item in models.IssuesType.PROJECT_INIT_LIST:  # ["任务", '功能', 'Bug']
            issues_type_object_list.append(models.IssuesType(project=instance, title=item))
        models.IssuesType.objects.bulk_create(issues_type_object_list)
        return JsonResponse({'status': True})
    return JsonResponse({'status':False,'errors':form.errors})

def project_star(request,project_type,project_id):

    """星标项目"""

    if project_type=='my':
        models.Project.objects.filter(id=project_id,creator=request.blog.user).update(star=True)
        return redirect('project_list')
    if project_type=='join':
        models.ProjectUser.objects.filter(project_id=project_id, user=request.blog.user).update(star=True)
        return redirect('project_list')
    return HttpResponse('请求错误')

def project_unstar(request,project_type,project_id):
    """取消星标"""
    if project_type == 'my':
        models.Project.objects.filter(id=project_id, creator=request.blog.user).update(star=False)
        return redirect('project_list')
    if project_type == 'join':
        models.ProjectUser.objects.filter(project_id=project_id, user=request.blog.user).update(star=False)
        return redirect('project_list')
    return HttpResponse('请求错误')

web/templates/contr_center.html
{% extends 'layout/basic.html' %}

web/templates/index.html
{% extends 'layout/basic.html' %}
{% load  static %}
{% block title %} 首页{% endblock %}

{%  block css %}
    <style>
        img{
            width: 100%;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        <img src="{% static 'image/index/index1.png' %}" alt="">
        <img src="{% static 'image/index/index1.png' %}" alt="">
        <img src="{% static 'image/index/index1.png' %}" alt="">
        <img src="{% static 'image/index/index1.png' %}" alt="">
    </div>
{% endblock %}

web/templates/project_list.html
{% extends 'layout/manage.html' %}
{% block css %}
    <style>
        .project{
            margin-top: 10px;
        }
        .panel-body{
            padding: 0;
            display:flex;
            justify-content: left;
            align-items: flex-start;
            flex-wrap: wrap;
        }
        .panel-body > .item{
            border-radius: 6px;
            width: 228px;
            border: 1px solid #dddddd;
            margin: 20px 10px;
        }
        .panel-body > .item:hover{
            border: 1px solid #f0ad4e;
        }
        .panel-body > .item > .title{
            height: 104px;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            border-top-left-radius: 6px;
            border-top-right-radius: 6px;
            font-size: 15px;
            text-decoration: none;
        }
        .panel-body > .item >.info{
            padding: 10px 10px;
            display: flex;
            justify-content: space-between;
            border-bottom-left-radius: 6px;
            border-top-right-radius: 6px;
            color: #8c8c8c;
        }
        .panel-body > .item > .info a{
            text-decoration: none;
        }

        .panel-body > .item > .info .fa-star{
            font-size: 18px;
        }
        .color_radio label{
            margin-left: 0;
            padding-left: 0;
        }
        .color-radio input[type="radio"]{
            display: none;
        }
        .color-radio input[type="radio"] + .cycle{
            display:inline-block;
            height: 25px;
            width: 25px;
            border-radius: 50%;
            border: 2px solid #dddddd;
        }
        .color-radio input[type="radio"]:checked + .cycle{
            border: 2px solid black;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="container-fluid project">
        <a class="btn btn-primary" data-toggle="modal" data-target="#addModal">
            <i class="fa fa-plus-circle" aria-hidden="true"></i>新建博客
        </a>
        <div class="panel panel-default">
          <div class="panel-heading"><i class="fa fa-star" aria-hidden="ture"></i>星标博客</div>
          <div class="panel-body">
              {% for item in project_dict.star %}
                  <div class="item">
                      <a href="{% url 'dashboard' project_id=item.value.id %}" class="title"
                      style="background-color: {{ item.value.get_color_display }};">{{ item.value.name }}</a>
                      <div class="info">
                          <div>
                              <a href="{% url 'project_unstar' project_type=item.type project_id=item.value.id%}">
                                  <i class="fa fa-star" aria-hidden="true" style="color: #f0ad4e"></i>
                              </a>
                              <span>{{ item.value.creator.username }}</span>
                          </div>
                          <div>
                              <i class="fa fa-user-o" aria-hidden="true"></i>
                              <span>{{ item.value.join_count }}</span>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading"><i class="fa fa-list" aria-hidden="true"></i>我创建的博客</div>
          <div class="panel-body">
            {% for item in project_dict.my %}
                  <div class="item">
                      <a href="{% url 'dashboard' project_id=item.id %}" class="title"
                      style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                      <div class="info">
                          <div>
                              <a href="{% url 'project_star' project_type='my' project_id=item.id %}">
                                  <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                              </a>
                              <span>{{ item.creator.username }}</span>
                          </div>
                          <div>
                              <i class="fa fa-user-o" aria-hidden="true"></i>
                              <span>{{ item.join_count }}</span>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading"><i class="fa fa-handshake-o" aria-hidden="true"></i>我参与的博客</div>
          <div class="panel-body">
            {% for item in project_dict.join %}
                  <div class="item">
                      <a href="{% url 'dashboard' project_id=item.id %}" class="title"
                      style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                      <div class="info">
                          <div>
                              <a href="{% url 'project_star' project_type='join' project_id=item.id %}">
                                  <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                              </a>
                              <span>{{ item.creator.username }}</span>
                          </div>
                          <div>
                              <i class="fa fa-user-o" aria-hidden="true"></i>
                              <span>{{ item.join_count }}</span>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          </div>
        </div>


    </div>
    <!-- Modal -->
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            <form id="addForm">
            {% csrf_token %}
              {%  for field in form %}
              <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="error-msg">{{ field.errors }}</span>
              </div>
              {% endfor %}
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button id="btnSubmit" type="button" class="btn btn-primary">Enter</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            bindSubmit();
        })

        function bindSubmit() {
            $('#btnSubmit').click(function () {
                $.ajax({
                    url:"{% url 'project_list' %}",
                    type:'POST',
                    data:$('#addForm').serialize(),
                    datatype:"JSON",
                    success:function (res) {
                        console.log(res);
                        if (res.status){
                            location.href=location.href;
                        }else{
                            $.each(res.errors,function(key,value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }
    </script>
{% endblock %}

web/templates/sign_up.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}用户注册{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg{
            color: red;
            position: absolute;
            font-size: 10px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="account">
        <div class="title">用户注册</div>
        <form id="form" method="post" novalidate>
            {% csrf_token %}
            {% for foo in form %}
                {% if foo.name == 'verification_code' %}
                    <div class="form-group">
                        <label for="{{ foo.id_for_label }}">{{ foo.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ foo }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-xs-5">
                                <input id="smsBtn" type="button" class="btn btn-default" value="点击获取验证码">
                            </div>
                        </div>
                    </div>
                 {% else %}
                    <div class="form-group">
                        <label for="{{ foo.id_for_label }}">{{ foo.label }}</label>
                        {{ foo }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
                <div class="row">
                    <div class="col-xs-3">
                        <input id="submit" type="button" class="btn btn-primary" value="注 册">
                    </div>
                </div>
        </form>
    </div>
{% endblock %}
{% block js %}
    <script>
        //页面加载完成自动执行函数
    $(function () {
        bindClickBtnSms()
        bindClickSubmit()
    });
    function bindClickSubmit() {
        $('#submit').click(function () {
            $.ajax({
                url:'{% url 'sign_up' %}',
                type:'POST',
                data:$('#form').serialize(),//获取数据
                dataType:'JSON',
                success:function (res) {
                    console.log(res);
                }
        })
        })



    }
    function bindClickBtnSms() {
        /*
        点击获取验证码按钮绑定事件
        找到输入框id，通过id获取手机号
         */
        $('#smsBtn').click(function () {

            $('.error-msg').empty();

            var mobilePhone=$('#id_mobile_phone').val()
            //发送ajax请求，将手机号发送过去
            $.ajax({
                url:'{% url 'send_sms' %}',
                type:'GET',
                data:{mobile_phone:mobilePhone,tpl:'sign_up' },
                datatype:'JSON',//将服务端返回的数据反序列化为字典
                success: function (res) {
                    if(res.status) {
                        sendSmsRemind();
                    }else{
                        //错误信息
                        $.each(res.error,function(key,value) {
                            $('#id_'+key).next().text(value[0]);
                        })
                    }
                }
            })
        })
    }
    function sendSmsRemind() {
        var $smsBtn=$('#smsBtn');
        $smsBtn.prop('disabled',true);
        var time=60;
        var remind = setInterval(function(){
            $smsBtn.val(time+'秒后重新发送');
            time=time-1;
            if (time<1){
                clearInterval(remind);
                $smsBtn.val('点击获取验证码').prop('disabled',false);
            }

            },1000)
        }
    </script>
{% endblock %}